### ISSUE TITLE
Inconsistency in estimate_ABL_height

### ISSUE THREAD

**Issue by DriesAllaerts** [a2e-mmc/mmctools#145]
https://github.com/a2e-mmc/mmctools/blob/00446aaef210871e2c12767a662e8208edf65f86/mmctools/helper_functions.py#L920-L922

The fucntion description says that the method using T looks for the height where the temperature gradient is smaller than some threshold. The implementation seems to do the opposite and looks for the height where the gradient exceeds the threshold.

**Comment by ewquon** [comment]
Thanks for catching that Dries!
