### ISSUE TITLE
Add coupling data class

### ISSUE THREAD

**Issue by ewquon** [a2e-mmc/mmctools#28]
To further simplify `coupling/WRF_to_SOWFA.ipynb`, because all of the output functions have similar inputs. E.g., `BCs_to_SOWFA(..., df,dateref,datefrom=datefrom,dateto=dateto,...)`. Thoughts, @DriesAllaerts ?

**Comment by DriesAllaerts** [comment]
@ewquon I believe this issue has been addressed properly in #36 and can be closed.

**Comment by ewquon** [comment]
Agreed
