### ISSUE TITLE
wrf directory conflict with wrf-python

### ISSUE THREAD

**Issue by phawbeck** [a2e-mmc/mmctools#53]
WRF-Python is loaded in simply as "wrf" and when the mmctools directory is added to my path, a conflict arrises between wrf-python and wrf. I recommend renaming "wrf" in mmctools to something like "wrf_tools"

**Comment by ewquon** [comment]
So this is a `PYTHONPATH` issue. As long as you don't directly add `mmctools` into your path (you should add the parent directory instead), then you won't have issues with trying to import the two different modules. Technically, `wrf` is the _module_ that's provided by wrf-python, whereas the `wrf` in `mmctools.wrf` is a _submodule_ that's provided by mmctools. This will be remedied when we provide a `setup.py` so mmctools are properly installed and you don't have to manually mess with your PYTHONPATH.

FYI: @cdraxl

**Comment by phawbeck** [comment]
Love it - glad we figured this out!
